#!/bin/bash
#http://stackoverflow.com/a/5255468/3692967
#variation http://stackoverflow.com/a/6708826/3692967

##this should be pretty straightforward to functionalize I think.
##


## arg handling
# translate long options to short
for arg
do
  delim=""
  case "$arg" in
    --help) args="${args:=}-h ";;
    --debug) args="${args:=}-d ";;
    --release) args="${args:=}-r ";;
    # pass through anything else
    *) [[ "${arg:0:1}" == "-" ]] || delim="\""
      args="${args:=}${delim}${arg}${delim} ";;
  esac
done
# reset the translated args
eval set -- ${args:=}
# now we can process with getopts
while getopts ":hdrf:" opt; do
  case $opt in
    h  )  usage ; exit 0 ;;
    d  ) DEBUG=1 ;;
    r  ) RELEASE=1 ;;
    f  ) FILENAME="$OPTARG" ;;
    \? ) usage "ERROR: invalid option given -$OPTARG" ; exit 1 ;;
    :)
      usage "ERROR: option -$OPTARG requires an argument "
      exit 1
    ;;
    *  ) usage "Unimplemented option: -$OPTARG"; exit 1 ;;
  esac
done
#since we have required options here.
if [[ $OPTIND -le 1 ]]; then usage "ERROR: No options were passed!"; exit 1; fi
